language: cpp

  
matrix:
  include:
  - env:
    - OCPN_TARGET=stretch-armhf
    - OCPN_BRANCH=ci
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-stretch-armhf.sh"
  - env:
    - OCPN_TARGET=buster-armhf
    - OCPN_BRANCH=ci
    - OCPN_PROJECT=${PACKAGE_NAME}
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-buster-armhf.sh"

#before_install:
#- 'echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne ''/-BEGIN
#  CERTIFICATE-/,/-END CERTIFICATE-/p'' | sudo tee -a /etc/ssl/certs/ca '
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: ci/generic-upload.sh
#  on:
#    branch: master
#    tags: false
#notifications:
#  email: false
#git:
#  depth: 10
#addons:
#  coverity_scan:
#    project:
#      name: OpenCPN/OpenCPN
#    notification_email: pavel@kalian.cz
#    build_command_prepend: mkdir -p build; cd build; cmake ..; make clean
#    build_command: make
#    branch_pattern: coverity_scan

branches:
  only:
    - ci

