project_identifier: opencpn
api_key: 9e946138b1a3ec9b3b8bdb2ae79a66d2
base_path: /home/dsr/Projects/oernc_pi

"preserve_hierarchy": true

files: [
 {
    "source" : "/po/oernc_pi.pot",
    "translation" : "/plugins/oernc_pi/po/%two_letters_code%.po",
    "translation" : "/plugins/oernc_pi/po/%locale_with_underscore%.po",

    }
]

